config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  resources :templates
  resources :questions
  resources :comments

  get 'athletes/info' => 'athletes#info', as: 'athlete'

  get 'athletes/index' => 'athletes#index', as: 'athlete_index'

  patch 'athletes/update' => 'athletes#update', as: 'athlete_update'

  post 'exercises/new' => 'exercise#new', as: 'exercise_new'

  get 'athletes/workout/:template_id' => 'athletes#workout', as: 'athletes_workout'

  get 'loggedworkouts' => 'logged_workouts#create', as: 'log_workout'

  post 'loggedworkouts' => 'logged_workouts#create', as: 'logged_workouts'

  get 'trainers/index' => 'trainers#index', as: 'trainer_index'

  get 'athletes/destroy' => 'athletes#destroy', as: 'athletes_destroy'

  patch 'athletes/info/:template_id' => 'athletes#info', as: 'athletes_info'

  devise_for :athletes, controllers: {
        sessions: 'athletes/sessions',
        registrations: 'athletes/registrations'
      }

      devise_for :trainers, controllers: {
        sessions: 'trainers/sessions',
        registrations: 'trainers/registrations'
      }

	root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

		belongs_to :trainer
		belongs_to :template, optional: true
		has_many :logged_workouts
		has_many :questions
		has_many :comments

	def rep_count
		if self.gender == "Male" 
			if goal == "Build Muscle"
				8
			elsif goal == "Lose Fat"
				"12 <br><i>Super set if possible!</i>".html_safe 
			else #goal == "transform"
				10
			end
		else # this would be female
			if goal == "Build Muscle"
				10
			elsif goal == "Lose Fat"
				"15 <br><i>Super set if possible!</i>".html_safe 
			else #goal == "transform"
				12
			end
		end	
	end	

	def assign_template
		if self.days_per_week == 3
			self.template_id = Template.where(name: "3 day workout").first.id
		elsif self.days_per_week == 4
			self.template_id = Template.where(name: "4 day workout").first.id
		else # 5 days per week
			self.template_id = Template.where(name: "5 day workout").first.id
		end
		save
	end

	def assign_calories
		if self.gender == "Female"
			if self.goal == "Lose Fat"
				self.calories = self.weight * 11
			elsif self.goal == "Build Muscle"
				self.calories = self.weight * 13
			else
				self.calories = self.weight * 12
			end
		else
			if self.goal == "Lose Fat"
				self.calories = self.weight * 12
			elsif
				self.calories = self.weight * 14
			else
				self.calories = self.weight * 13
			end
		end
		save
	end

	def assign_macros
		if self.goal == "Lose Fat"
			self.carbs = self.weight * 0.75
			self.protein = self.weight
			self.fats = self.weight * 0.3

		elsif self.goal == "Build Muscle"
			self.carbs = self.weight * 1.2
			self.protein = self.weight * 1.2
			self.fats = self.weight * 0.5

		else
			self.carbs = self.weight
			self.protein = self.weight
			self.fats = self.weight * 0.4
		end
		save
	end

	def last_seven_days
		self.logged_workouts.where("created_at >= ?", Time.now - 7.days)
	end

end

app/controllers/athletes/confirmations_controller.rb
class Athletes::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/athletes/omniauth_callbacks_controller.rb
class Athletes::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/athletes/passwords_controller.rb
class Athletes::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/athletes/registrations_controller.rb
class Athletes::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
    @athlete.assign_template
    @athlete.assign_calories
    @athlete.assign_macros
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :home_gym, :phone, :height, :weight, :body_fat, :goal_weight, :gender, :age, :days_per_week, :goal, :trainer_id, :template_id, :calories, :carbs, :protein, :fats, :subscription_type, :card_number, :card_cvc, :card_expiration])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :home_gym, :phone, :height, :weight, :body_fat, :goal_weight, :gender, :age, :days_per_week, :goal, :trainer_id, :template_id, :calories, :carbs, :protein, :fats, :subscription_type, :card_number, :card_cvc, :card_expiration])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    athlete_path
  end


  def after_update_path_for(resource)
    athlete_index_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/athletes/sessions_controller.rb
class Athletes::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    athlete_index_path(resource)
  end

  def after_sign_in_path_for(resource)
    athlete_index_path(resource)
  end
end

app/controllers/athletes/unlocks_controller.rb
class Athletes::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :authenticate_athlete!, except: [:index]
  def info
  	@athlete = current_athlete
  end

  def update
  	@athlete = current_athlete
  	@athlete.update_attributes(athlete_params)
  	@athlete.assign_template
  	@athlete.assign_calories
  	@athlete.assign_macros
    if @athlete.template_id == nil
      @athlete.template.id = 1
    else
      
    end
    redirect_to athlete_index_path
  end

  def index
    @question = Question.new
    @comment = Comment.new
    @exercises = Exercise.all
    @trainer = current_trainer
  	@athlete = current_athlete || Athlete.find(params[:id])
    if @athlete.template_id == nil
      @athlete.template_id = 1
    else
      
    end
  	@template = @athlete.template
    @new_template = Template.new
  	@workouts = @template.workouts
  	@template_exercises = {	}
  	@workouts.each do |workout|
  		@template_exercises[workout.day_number.to_s.to_sym] = []
  	end
  	@workouts.each do |workout|
  		@template_exercises[workout.day_number.to_s.to_sym] << workout.exercise
  	end
  end

  def workout
  	@athlete = current_athlete
  	@template = Template.find(params[:template_id])
  	@workouts = @template.workouts.where(day_number: params[:day])
  	@logged_workout = LoggedWorkout.new
  end

  def destroy
    Athlete.find(params[:id]).destroy
    redirect_to home_index_path
  end


  private

  def athlete_params
  	params.require(:athlete).permit(:gender, :age, :height, :weight, :goal_weight, :body_fat, :goal, :days_per_week, :template_id, :calories, :carbs, :protein, :fats, :subscription_type, :card_number, :card_cvc, :card_expiration)
  end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/index.html.erb
<% if athlete_signed_in? %>
	<div class="dashboard">
		<div class="row">
			<div class="card col-md-4" id="athlete_info">
			<h1><%= @athlete.first_name %> <%= @athlete.last_name %></h1>
			<i>Click to edit info</i>
				<div class="info">
				<h1></h1>
					<%= form_for(@athlete, :url => athlete_update_path) do |f| %>
						
					  <div class="field profile">
					    Home Gym: <%= f.text_field :home_gym %>
					  </div>

					  <div class="field profile">
					    Age: <%= f.text_field :age %>
					  </div>

					  <div class="field profile">
					    Phone: <%= f.text_field :phone %>
					  </div>

					  <div class="field profile">
					    Email: <%= f.email_field :email %>
					  </div>

					  <div class="field profile">
					    Height: <%= f.text_field :height %>
					  </div>

					  <div class="field profile">
					    Weight: <%= f.text_field :weight %>
					  </div>

					  <div class="field profile">
					    Goal Weight: <%= f.text_field :goal_weight %>
					  </div>

					   <div class="field profile">
					    Body Fat Range: <%= f.select :body_fat, ['0-5%', '10-15%', '20-25%', '25% +'], class: "select" %>
					  </div>

					  <div class="field profile">
					    Goal: <%= f.select :goal, ['Build Muscle', 'Lose Fat', 'Just Get To The Gym!'], class: "select" %>
					  </div>


					  <div class="field profile">
					    Days Per Week: <%= f.select :days_per_week, [3,4,5], class: "select" %>
					  </div>

					  <div class="field profile">
					    Days Per Week: <%= f.select :subscription_type, ["Basic", "Premium"], class: "select" %>
					  </div>

					  <div class="actions">
					    <%= f.submit "Update", class: "btn", id: "update" %>
					  </div> 

					  <%= link_to "Cancel my account", athlete_registration_path, data: { confirm: "Are you sure?" }, method: :delete, class: 'btn' %>
					<% end %>
				</div>
			</div>
				<div class="card col-md-4">	
				<h1><%= @template.name %></h1>
					<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#scheduleModal">
						  <h2>View Schedule</h2>
					</button> 
				</div>


			<div class="card col-md-4">
			<h1>Logged Workouts</h1>
				<div class="logged_workout">
				<% @athlete.last_seven_days.each do |logged_workout| %>
					<%= time_ago_in_words(logged_workout.created_at) %> ago <br>
					<%= logged_workout.exercise.name %> <br>
					Sets: <%= logged_workout.sets %>
					Reps: <%= logged_workout.rep_count %>
					Weight: <%= logged_workout.weight %> <br>
					<%= logged_workout.comment %>
					<hr>
				<% end %>
			</div>
		</div>

		<div class="row">
			<div class="card col-md-4">
				<h3>Questions</h3>
				<button type="button" class="btn btn-primary btn-sl" data-toggle="modal" data-target="#myQuestionModal" id="questionbtn">
						  <i>New Question</i>
				</button> <br>
				<% @athlete.questions.each do |question| %>
					<h3><%= question.content %></h3> <br>
					<% question.comments.each do |comment|  %>
						<%= comment.content %> <br>
					<% end %>
				
				<%= form_for (@comment) do |f| %>

				  <div class="field">
				    <%= f.text_area :content, class: "loginput" %>
				    <%= hidden_field_tag( "comment[question_id]",  question.id) %>
					<%= hidden_field_tag( "comment[athlete_id]",  @athlete.id) %>
				  </div>

				  <div class="actions">
				    <%= f.submit "Save", class: "btn" %>
				  </div>

				<% end %>
			<% end %>
			</div>
			
			<div class="card col-md-4">
				<% if @athlete.goal == "Build Muscle" %>
					<h1>Macros to Bulk!</h1>
				<% elsif @athlete.goal == "Lose Fat" %>
					<h1>Macros to Lose Fat!</h1>
				<% else %>
					<h1>Suggested Macros </h1>
				<% end %>
				<h3 id="calories">Suggested Calories: <%= @athlete.calories %></h3>
				<h3 id="carbs">Suggested Carbs: <%= @athlete.carbs %></h3>
				<h3 id="protein">Suggested Protein: <%= @athlete.protein %></h3>
				<h3 id="fats">Suggested Fats: <%= @athlete.fats %></h3>

			</div>


			<div class="card col-md-4">
				<h1>Daily Nutrition Log</h1>
				<div class="macrolog">
					<input type="number" placeholder="Calories" id="caloriecounter"> <br> <br>
					<input type="number" placeholder="Carbs" id="carbcounter"> <br> <br>
					<input type="number" placeholder="Protien" id="proteincounter"> <br> <br>
					<input type="number" placeholder="Fats" id="fatcounter"> <br>
					<button class="btn" id="counterbtn">Submit</button>
				</div>
				<div class="dailymacros">
					<h3 id="caloriestoday"></h3>
					<h3 id="carbstoday"></h3>
					<h3 id="proteinstoday"></h3>
					<h3 id="fatstoday"></h3>
				</div>
			</div>
		</div>
	</div>

	<div class="modal fade" id="scheduleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel"><h1><%= @template.name %></h1></h4>
	      </div>
	      <div class="modal-body">
				<%  @template_exercises.each do |day, exercises| %>
					<div class="schedule">
					<h2>Day <%= day %><%= link_to "Start Workout", athletes_workout_path(@template, day: day) %></h2>
						<% exercises.each do |exercise| %>
						  	<h3><%= exercise.name %></h3>
						  <% end %>
					</div>
				<% end %>        
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>

	<div class="modal fade" id="myQuestionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel"><h1>Ask The Trainer A Question!</h1></h4>
	      </div>
	      <div class="modal-body">
			<%= form_for (@question) do |f| %>

			  <div class="field">
			    <%= f.label :content %><br />
			    <%= f.text_area :content %>
			  </div>

			  <div class="actions">
			    <%= f.submit "Save", class: "btn" %>
			  </div>

			<% end %>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
	
<% else %>
	<div class="dashboard">
		<div class="row">
			<div class="card col-md-4" id="athlete_info">
			<h1><%= @athlete.first_name %> <%= @athlete.last_name %></h1>
			<h3>Weight: <%= @athlete.weight %></h3>
			<h3>Goal: <%= @athlete.goal %></h3>
			<h3>Goal Weight: <%= @athlete.goal_weight %></h3>
			<h3>Days Per Week: <%= @athlete.days_per_week %></h3>
			<h3>Gym: <%= @athlete.home_gym %></h3>
			</div>
				
			<div class="card col-md-4">
				<h1><%= @template.name %></h1>
			</div>

			<div class="card col-md-4">
			<h1>Logged Workouts</h1>
				<% @athlete.last_seven_days.each do |logged_workout| %>
					<%= time_ago_in_words(logged_workout.created_at) %> ago <br>
					<%= logged_workout.exercise.name %> <br>
					Sets: <%= logged_workout.sets %>
					Reps: <%= logged_workout.rep_count %>
					Weight: <%= logged_workout.weight %> <br>
					<%= logged_workout.comment %>
					<hr>
				<% end %>
			</div>
		</div>

		<div class="row">
			<div class="card col-md-4">
				<h3>Questions</h3>
				<% @athlete.questions.each do |question| %>
					<h3><%= question.content %></h3> 
					<% question.comments.each do |comment|  %>
						<%= comment.content %> <br>
					<% end %>
					<%= form_for (@comment) do |f| %>

					  <div class="field">
					    <%= f.text_area :content, class: "loginput" %>
					  </div>
						<%= hidden_field_tag( "comment[question_id]",  question.id) %>
						<%= hidden_field_tag( "comment[trainer_id]",  @trainer.id) %>
						<%= hidden_field_tag( "comment[athlete_id]",  @athlete.id) %>
					  <div class="actions">
					    <%= f.submit "Save Comment", class: "btn" %>
					  </div>

					<% end %>
				<% end %>
			</div>
			
			<div class="card col-md-4">
				<% if @athlete.goal == "Build Muscle" %>
					<h1>Macros to Bulk!</h1>
				<% elsif @athlete.goal == "Lose Fat" %>
					<h1>Macros to Lose Fat!</h1>
				<% else %>
					<h1>Suggested Macros</h1>
				<% end %>
				<h3>Suggested Calories: <%= @athlete.calories %></h3>
				<h3>Suggested Carbs: <%= @athlete.carbs %></h3>
				<h3>Suggested Protein: <%= @athlete.protein %></h3>
				<h3>Suggested Fats: <%= @athlete.fats %></h3>

			</div>


			<div class="card col-md-4">
					
			</div>
		</div>
	</div>

	<div id="templateform" class="hiddendivs">
		<button class="exit">X</button>
		<%= render 'templates/custom_template' %>
	</div>
	
<% end %>

app/views/athletes/info.html.erb
<div class="updatebackground">

</div>
<div id="edit_athlete">
	<%= form_for(@athlete, :url => athlete_update_path)  do |f| %>
		<div class="form">
		  <div class="field">
		    <%= f.label :gender %><br />
		    <%= f.select :gender,["Male", "Female"], autofocus: true %>
		  </div>

		  <div class="field">
		    <%= f.label :age %><br />
		    <%= f.text_field :age%>
		  </div>

		  <div class="field">
		    <%= f.label :height %> <i>in inches</i><br />
		    <%= f.text_field :height %>
		  </div>

		  <div class="field">
		    <%= f.label :weight %> <i>in pounds</i> <br />
		    <%= f.text_field :weight %>
		  </div>

		   <div class="field">
		    <%= f.label :body_fat %><br />
		    <%= f.select :body_fat, ['0-5%', '10-15%', '20-25%', '25% +'] %>
		  </div>

		  <div class="field">
		    <%= f.label :goal_weight %><br />
		    <%= f.text_field :goal_weight %>
		  </div>

		  <div class="field">
		    <%= f.label :goal %><br />
		    <%= f.select :goal, ['Build Muscle', 'Lose Fat', 'Just Get To The Gym!'] %>
		  </div>

		  <div class="field">
		    <%= f.label :days_per_week %><br />
		    <%= f.select :days_per_week, [3,4,5] %>
		  </div>


		  <div class="actions">
		    <%= f.submit "Update", class: "btn", id: "updatebtn" %>
		  </div>
	  </div>
	<% end %>
</div>

app/views/athletes/workout.html.erb
<% if @athlete.gender == "Female" %>
	<div class="girllogbackground">
	</div>
<% else %>
	<div class="logbackground">
	</div>
<% end %>

<div class="form">
	<div class="logform">
		<h3>3 sets of <%= @athlete.rep_count %></h3>
		<%= form_for @logged_workout  do |f| %>
			<%  @workouts.each do |workout| %>
				<div class="schedule">
					<%= workout.exercise.name %> <br>
					<div class="field">
						<%= f.text_field :sets, placeholder: "Sets", name: "logged_workout[#{workout.exercise.name}[sets]]", class: "loginput"  %> <br>
					</div>
					<div class="field">
				    	<%= f.text_field :rep_count, placeholder: "Reps", name: "logged_workout[#{workout.exercise.name}[rep_count]]", class: "loginput"  %> <br>
				    </div>
				    <div class="field">
				    	<%= f.text_field :weight, placeholder: "Weight", name: "logged_workout[#{workout.exercise.name}[weight]]", class: "loginput" %> <br>
				    </div>
				    <div class="field">	
	 			    	<%= f.text_area :comment, placeholder: "Comment", name: "logged_workout[#{workout.exercise.name}[comment]]", class: "loginput" %> <br>
	 			    </div>
	 			    <div class="field">
	 			    	<%= hidden_field_tag( "logged_workout[#{workout.exercise.name}[athlete_id]]", @athlete.id) %>
	 			    	<%= hidden_field_tag( "logged_workout[#{workout.exercise.name}[template_id]]", @athlete.template.id) %>
	 			    	<%= hidden_field_tag( "logged_workout[#{workout.exercise.name}[exercise_id]]", workout.exercise.id) %>
	 			    </div>
				</div>
			<% end %> 
			<%= f.submit "Save Workout", class: "btn" %>
		<% end -%>
	</div>
</div>