config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  resources :templates
  resources :questions
  resources :comments

  get 'athletes/info' => 'athletes#info', as: 'athlete'

  get 'athletes/index' => 'athletes#index', as: 'athlete_index'

  patch 'athletes/update' => 'athletes#update', as: 'athlete_update'

  post 'exercises/new' => 'exercise#new', as: 'exercise_new'

  get 'athletes/workout/:template_id' => 'athletes#workout', as: 'athletes_workout'

  get 'loggedworkouts' => 'logged_workouts#create', as: 'log_workout'

  post 'loggedworkouts' => 'logged_workouts#create', as: 'logged_workouts'

  get 'trainers/index' => 'trainers#index', as: 'trainer_index'

  get 'athletes/destroy' => 'athletes#destroy', as: 'athletes_destroy'

  patch 'athletes/info/:template_id' => 'athletes#info', as: 'athletes_info'

  devise_for :athletes, controllers: {
        sessions: 'athletes/sessions',
        registrations: 'athletes/registrations'
      }

      devise_for :trainers, controllers: {
        sessions: 'trainers/sessions',
        registrations: 'trainers/registrations'
      }

	root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

		belongs_to :trainer
		belongs_to :template, optional: true
		has_many :logged_workouts
		has_many :questions
		has_many :comments

	def rep_count
		if self.gender == "Male" 
			if goal == "Build Muscle"
				8
			elsif goal == "Lose Fat"
				"12 <br><i>Super set if possible!</i>".html_safe 
			else #goal == "transform"
				10
			end
		else # this would be female
			if goal == "Build Muscle"
				10
			elsif goal == "Lose Fat"
				"15 <br><i>Super set if possible!</i>".html_safe 
			else #goal == "transform"
				12
			end
		end	
	end	

	def assign_template
		if self.days_per_week == 3
			self.template_id = Template.where(name: "3 day workout").first.id
		elsif self.days_per_week == 4
			self.template_id = Template.where(name: "4 day workout").first.id
		else # 5 days per week
			self.template_id = Template.where(name: "5 day workout").first.id
		end
		save
	end

	def assign_calories
		if self.gender == "Female"
			if self.goal == "Lose Fat"
				self.calories = self.weight * 11
			elsif self.goal == "Build Muscle"
				self.calories = self.weight * 13
			else
				self.calories = self.weight * 12
			end
		else
			if self.goal == "Lose Fat"
				self.calories = self.weight * 12
			elsif
				self.calories = self.weight * 14
			else
				self.calories = self.weight * 13
			end
		end
		save
	end

	def assign_macros
		if self.goal == "Lose Fat"
			self.carbs = self.weight * 0.75
			self.protein = self.weight
			self.fats = self.weight * 0.3

		elsif self.goal == "Build Muscle"
			self.carbs = self.weight * 1.2
			self.protein = self.weight * 1.2
			self.fats = self.weight * 0.5

		else
			self.carbs = self.weight
			self.protein = self.weight
			self.fats = self.weight * 0.4
		end
		save
	end

	def last_seven_days
		self.logged_workouts.where("created_at >= ?", Time.now - 7.days)
	end

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :trainer, optional: true
	belongs_to :athlete, optional: true
	belongs_to :question
end

app/models/exercise.rb
class Exercise < ApplicationRecord
	has_many :workouts
	has_many :template, through: :workouts
	has_many :logged_workouts
end

app/models/logged_workout.rb
class LoggedWorkout < ApplicationRecord
	belongs_to :athlete
	belongs_to :template
	belongs_to :exercise

end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :athlete
	has_many :comments
end

app/models/template.rb
class Template < ApplicationRecord
	has_many :athletes
	has_many :workouts
	has_many :exercises, through: :workouts
	has_many :logged_workouts
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

		has_many :athletes
		has_many :comments
end

app/models/workout.rb
class Workout < ApplicationRecord
	belongs_to :template
	belongs_to :exercise
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :authenticate_athlete!, except: [:index]
  def info
  	@athlete = current_athlete
  end

  def update
  	@athlete = current_athlete
  	@athlete.update_attributes(athlete_params)
  	@athlete.assign_template
  	@athlete.assign_calories
  	@athlete.assign_macros
    if @athlete.template_id == nil
      @athlete.template.id = 1
    else
      
    end
    redirect_to athlete_index_path
  end

  def index
    @question = Question.new
    @comment = Comment.new
    @exercises = Exercise.all
    @trainer = current_trainer
  	@athlete = current_athlete || Athlete.find(params[:id])
    if @athlete.template_id == nil
      @athlete.template_id = 1
    else
      
    end
  	@template = @athlete.template
    @new_template = Template.new
  	@workouts = @template.workouts
  	@template_exercises = {	}
  	@workouts.each do |workout|
  		@template_exercises[workout.day_number.to_s.to_sym] = []
  	end
  	@workouts.each do |workout|
  		@template_exercises[workout.day_number.to_s.to_sym] << workout.exercise
  	end
  end

  def workout
  	@athlete = current_athlete
  	@template = Template.find(params[:template_id])
  	@workouts = @template.workouts.where(day_number: params[:day])
  	@logged_workout = LoggedWorkout.new
  end

  def destroy
    Athlete.find(params[:id]).destroy
    redirect_to home_index_path
  end


  private

  def athlete_params
  	params.require(:athlete).permit(:gender, :age, :height, :weight, :goal_weight, :body_fat, :goal, :days_per_week, :template_id, :calories, :carbs, :protein, :fats, :subscription_type, :card_number, :card_cvc, :card_expiration)
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Exercise.all
  end

  def new
    @exercise = Exercise.new
  end

  def edit
  end

  def show
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      redirect_to trainer_index_path
    else
      
    end
  end

  def update
  end

  def destroy
    Exercise.find(params[:id]).destroy
    redirect_to trainer_index_path
  end

  private
  def exercise_params
    params.require(:exercise).permit(:name, :category, :primary_muscle, :secondary_muscle, :instruction)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logged_workouts_helper.rb
module LoggedWorkoutsHelper
end

app/helpers/quetsions_helper.rb
module QuetsionsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_all_exercises.html.erb
<div id="all_exercises">
	<div class="categories">
		<h1>Arms</h1>
		<% @exercises.where(category: "Arms").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Shoulders</h1>
		<% @exercises.where(category: "Shoulders").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Legs</h1>
		<% @exercises.where(category: "Legs").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Chest</h1>
		<% @exercises.where(category: "Chest").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Back</h1>
		<% @exercises.where(category: "Back").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Core</h1>
		<% @exercises.where(category: "Core").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
</div>

app/views/exercises/_delete_exercise.html.erb
<div class="row" id="all_exercises">
	<div class="categories">
		<h1>Arms</h1>
		<% @exercises.where(category: "Arms").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<p>Instruction: <%= exercise.instruction %></p>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Shoulders</h1>
		<% @exercises.where(category: "Shoulders").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<p>Instruction: <%= exercise.instruction %></p>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Legs</h1>
		<% @exercises.where(category: "Legs").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<p>Instruction: <%= exercise.instruction %></p>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Chest</h1>
		<% @exercises.where(category: "Chest").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<p>Instruction: <%= exercise.instruction %></p>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Back</h1>
		<% @exercises.where(category: "Back").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<p>Instruction: <%= exercise.instruction %></p>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
	<hr>
	<div class="categories">
		<h1>Core</h1>
		<% @exercises.where(category: "Core").each do |exercise| %>
			<div class="specific_exercise" name="<%= exercise.name %>" value="<%= exercise.id %>">
				<h3>Name: <%= exercise.name%></h3>
				<p>Instruction: <%= exercise.instruction %></p>
				<%= link_to "Delete Exercise", exercise_path(exercise), method: :delete, class: "btn" %>
			</div>
		<% end %>
	</div>
</div>

app/views/exercises/_new_exercise_html.erb
<%= form_for(:exercise, :url => new_exercise_path(:exercise)) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, ["Arms", "Legs", "Back", "Chest", "Core", "Shoulders"] %>
  </div>

  <div class="field">
    <%= f.label :primary_muscle %><br />
    <%= f.text_field :primary_muscle %>
  </div>

  <div class="field">
    <%= f.label :secondary_muscle %><br />
    <%= f.text_field :secondary_muscle %>
  </div>

  <div class="field">
    <%= f.label :instruction %><br />
    <%= f.text_area :instruction %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn" %>
  </div>

<% end %>

app/views/exercises/create.html.erb
<h1>Exercises#create</h1>
<p>Find me in app/views/exercises/create.html.erb</p>

app/views/exercises/destroy.html.erb
<h1>Exercises#destroy</h1>
<p>Find me in app/views/exercises/destroy.html.erb</p>

app/views/exercises/edit.html.erb
<h1>Exercises#edit</h1>
<p>Find me in app/views/exercises/edit.html.erb</p>

app/views/exercises/new.html.erb
<h1>Exercises#new</h1>
<p>Find me in app/views/exercises/new.html.erb</p>

<h2>Create New Exercise</h2>

<%= form_for (@exercise) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, ["Arms", "Legs", "Back", "Chest", "Core", "Shoulders"] %>
  </div>

  <div class="field">
    <%= f.label :primary_muscle %><br />
    <%= f.text_field :primary_muscle %>
  </div>

  <div class="field">
    <%= f.label :secondary_muscle %><br />
    <%= f.text_field :secondary_muscle %>
  </div>

  <div class="field">
    <%= f.label :instruction %><br />
    <%= f.text_area :instruction %>
  </div>

  <div class="actions">
    <%= f.submit "Save" %>
  </div>

<% end %>

app/views/exercises/show.html.erb
<h1>Exercises#show</h1>
<p>Find me in app/views/exercises/show.html.erb</p>

app/views/exercises/update.html.erb
<h1>Exercises#update</h1>
<p>Find me in app/views/exercises/update.html.erb</p>