config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  resources :templates
  resources :questions
  resources :comments

  get 'athletes/info' => 'athletes#info', as: 'athlete'

  get 'athletes/index' => 'athletes#index', as: 'athlete_index'

  patch 'athletes/update' => 'athletes#update', as: 'athlete_update'

  post 'exercises/new' => 'exercise#new', as: 'exercise_new'

  get 'athletes/workout/:template_id' => 'athletes#workout', as: 'athletes_workout'

  get 'loggedworkouts' => 'logged_workouts#create', as: 'log_workout'

  post 'loggedworkouts' => 'logged_workouts#create', as: 'logged_workouts'

  get 'trainers/index' => 'trainers#index', as: 'trainer_index'

  get 'athletes/destroy' => 'athletes#destroy', as: 'athletes_destroy'

  patch 'athletes/info/:template_id' => 'athletes#info', as: 'athletes_info'

  devise_for :athletes, controllers: {
        sessions: 'athletes/sessions',
        registrations: 'athletes/registrations'
      }

      devise_for :trainers, controllers: {
        sessions: 'trainers/sessions',
        registrations: 'trainers/registrations'
      }

	root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

		has_many :athletes
		has_many :comments
end

app/controllers/trainers/confirmations_controller.rb
class Trainers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/trainers/omniauth_callbacks_controller.rb
class Trainers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/trainers/passwords_controller.rb
class Trainers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/trainers/registrations_controller.rb
class Trainers::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    trainer_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/trainers/sessions_controller.rb
class Trainers::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    trainer_index_path(resource)
  end
end

app/controllers/trainers/unlocks_controller.rb
class Trainers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
	before_action :authenticate_trainer!
	def index
		@athletes = Athlete.all
		@exercises = Exercise.all
		@templates = Template.all
		@exercise = Exercise.new
		@template = Template.new
		@trainer = current_trainer
	end

	def new

	end

	def edit
	end

	def show
	end

	def create
	end

	def update
		@trainer = current_trainer
		@trainer.update_attributes(trainer_params)
	end

	def destroy
	end

	private

	  def trainer_params
	  	params.require(:trainer).permit(:email)
	  end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/index.html.erb
<div class="dashboard trainerdashboard">
	<div class="row">
		
		<div class="trainer_card col-md-3" >
			<h1> My Athletes </h1>
			<p id="basic">Basic Athletes: <%= @athletes.where(subscription_type: "Basic").count %></p>
			<p id="premium">Premium Athletes: <%= @athletes.where(subscription_type: "Premium").count %></p><br>
			<% @athletes.where(subscription_type: "Basic").each do |athlete| %></h5>
				
				<%= link_to(  "#{athlete.first_name} #{athlete.last_name} ", athlete_index_path(id: athlete.id), :class => "btn") %> <br>
				
			<% end %>
			<% @athletes.where(subscription_type: "Premium").each do |athlete| %>
				
				<%= link_to(  "#{athlete.first_name} #{athlete.last_name} ", athlete_index_path(id: athlete.id), :class => "premiumbtn btn") %> <br>
				
			<% end %>
		</div>

		<div class="trainer_card col-md-3">
			<h2>Create New Exercise</h2>
			<%= form_for(@exercise) do |f| %>

			  <div class="field">
			    <%= f.label :name %><br />
			    <%= f.text_field :name %>
			  </div>

			  <div class="field">
			    <%= f.label :category %><br />
			    <%= f.select :category, ["Arms", "Legs", "Back", "Chest", "Core", "Shoulders"] %>
			  </div>

			  <div class="field">
			    <%= f.label :primary_muscle %><br />
			    <%= f.text_field :primary_muscle %>
			  </div>

			  <div class="field">
			    <%= f.label :secondary_muscle %><br />
			    <%= f.text_field :secondary_muscle %>
			  </div>

			  <div class="field">
			    <%= f.label :instruction %><br />
			    <%= f.text_area :instruction, class: "loginput" %>
			  </div>

			  <div class="actions">
			    <%= f.submit "Save", class: "btn" %>
			  </div>

			<% end %>
		</div>


	<div class="trainer_card col-md-3">
	<h1>Athletes Questions</h1>
		<% @athletes.each do |athlete| %>
		 	<% athlete.questions.each do |question| %>
				<% if !question.read %> 
					<%= athlete.first_name %> <%= athlete.last_name %>: 
					<%= question.content %>
					<%= link_to('Visit Page', athlete_index_path(id: athlete.id), :id => "smallbutton") %> <hr>
				<% else %>
				<% end %>
			<% end %>
		<% end %>		
	</div>

	<div class="trainer_card col-md-3">
	<h1>All Templates</h1>
	<% @templates.each do |template| %>		
		  <h3 id="templatename"><%= template.name%></h3>		    
		<br>
		<% @athletes.where(template_id: template.id).each do |athlete| %>
			<%= athlete.first_name %> <%= athlete.last_name %> <br>
		<% end %> <hr>
	<% end %>		
	</div>
</div>

<div id="templateform" class="hiddendivs">
<button class="exit">X</button>
	<%= render 'templates/new' %>
</div>

<div id="exerciseform" class="hiddendivs">
<button class="exit">X</button>
	<%= render 'exercises/delete_exercise' %>
</div>